#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[[ -f "$ROOT/.env" ]] || { echo "missing $ROOT/.env; run make env" >&2; exit 1; }
# shellcheck disable=SC1091
source "$ROOT/.env"
# Per-run identity (session IDs + run id) overrides the stable .env defaults so
# this run's shim/adapter traffic is isolated from earlier runs. Generated by
# scripts/new-demo-run.sh (via make preflight); require it so components never
# silently fall back to the stable sessions.
[[ -f "$ROOT/.state/demo-run.env" ]] || { echo "missing $ROOT/.state/demo-run.env; run 'make preflight' (or scripts/new-demo-run.sh) first" >&2; exit 1; }
# shellcheck disable=SC1091
source "$ROOT/.state/demo-run.env"
make -C "$ROOT" build
mkdir -p "$ROOT/.state/logs"

start() {
  local name="$1"
  local executable="$2"
  shift 2
  local pidfile="$ROOT/.state/$name.pid"
  if [[ -f "$pidfile" ]]; then
    local old_pid old_executable
    IFS=$'\t' read -r old_pid old_executable < "$pidfile" || true
    if [[ "$old_pid" =~ ^[0-9]+$ ]] && kill -0 "$old_pid" 2>/dev/null; then
      echo "$name already appears to be running as pid $old_pid; run scripts/stop-components.sh" >&2
      exit 1
    fi
    rm -f "$pidfile"
  fi
  "$@" >"$ROOT/.state/logs/$name.log" 2>&1 &
  local pid=$!
  printf '%s\t%s\n' "$pid" "$executable" > "$pidfile"
}

start release-mcp "$ROOT/bin/release-mcp-server" \
  env RELEASE_MCP_BIND="${RELEASE_MCP_BIND:-127.0.0.1:8090}" \
      RELEASE_MCP_RECEIPTS="${RELEASE_MCP_RECEIPTS:-$ROOT/.state/release-mcp-receipts.jsonl}" \
      "$ROOT/bin/release-mcp-server"
start copilot-shim "$ROOT/bin/copilot-session-shim" \
  env TALON_GATEWAY="$TALON_GATEWAY" \
      TALON_COPILOT_SESSION_ID="$TALON_COPILOT_SESSION_ID" \
      COPILOT_SHIM_BIND="${COPILOT_SHIM_BIND:-127.0.0.1:8079}" \
      "$ROOT/bin/copilot-session-shim"
start zendesk-adapter "$ROOT/bin/zendesk-adapter" \
  env ZENDESK_ADAPTER_TOKEN="$ZENDESK_ADAPTER_TOKEN" \
      TALON_GATEWAY="$TALON_GATEWAY" \
      TALON_CUSTOMER_SUPPORT_KEY="$TALON_CUSTOMER_SUPPORT_KEY" \
      TALON_CUSTOMER_SUPPORT_PROVIDER="${TALON_CUSTOMER_SUPPORT_PROVIDER:-local-llama}" \
      TALON_CUSTOMER_SUPPORT_MODEL="${TALON_CUSTOMER_SUPPORT_MODEL:-llama3.2:1b}" \
      TALON_DEMO_RUN_ID="${TALON_DEMO_RUN_ID:-}" \
      ZENDESK_ADAPTER_BIND="${ZENDESK_ADAPTER_BIND:-127.0.0.1:8443}" \
      "$ROOT/bin/zendesk-adapter"

# Readiness gate (review finding H4): a component that fails to bind used to
# leave a dead pidfile behind while the script reported success. Fail loudly
# and clean up everything this invocation started instead.
wait_healthy() {
  local name="$1" url="$2"
  for _ in $(seq 1 100); do
    if curl --fail --silent --max-time 1 "$url" >/dev/null 2>&1; then
      return 0
    fi
    sleep 0.05
  done
  echo "$name did not become healthy at $url; log follows" >&2
  cat "$ROOT/.state/logs/$name.log" >&2 || true
  "$ROOT/scripts/stop-components.sh" || true
  exit 1
}
# The shim has no local /health -- every path is proxied to Talon, which is
# started separately. Its readiness check therefore only requires the shim
# to answer HTTP at all (any status), not a healthy upstream.
wait_listening() {
  local name="$1" url="$2"
  for _ in $(seq 1 100); do
    local code
    code="$(curl --silent --output /dev/null --write-out '%{http_code}' --max-time 1 "$url" 2>/dev/null || true)"
    if [[ "$code" != "000" && -n "$code" ]]; then
      return 0
    fi
    sleep 0.05
  done
  echo "$name is not accepting HTTP connections at $url; log follows" >&2
  cat "$ROOT/.state/logs/$name.log" >&2 || true
  "$ROOT/scripts/stop-components.sh" || true
  exit 1
}

wait_healthy release-mcp "http://${RELEASE_MCP_BIND:-127.0.0.1:8090}/health"
wait_listening copilot-shim "http://${COPILOT_SHIM_BIND:-127.0.0.1:8079}/health"
wait_healthy zendesk-adapter "http://${ZENDESK_ADAPTER_BIND:-127.0.0.1:8443}/health"

echo 'Started local integration components.'
